import { Parcel, DashboardStats, ParcelStatusInfo } from '@/types/parcel.types';
import Colors from './Colors';

// Neighborhoods and districts of Oujda (وجدة)
export const OUJDA_NEIGHBORHOODS = [
  'Centre-Ville (وسط المدينة)',
  'Boulevard Mohammed V',
  'Quartier Lazaret (لازاريت)',
  'Hay Al Qods (حي القدس)',
  'Hay Salam (حي السلام)',
  'Hay Al Hikma (حي الحكمة)',
  'Sidi Yahya (سيدي يحيى)',
  'Hay Andalous (حي الأندلس)',
  'Hay Al Wahda (حي الوحدة)',
  'Mir Ali (مير علي)',
  'Village Touba (قرية طوبة)',
  'Hay Ennasr (حي النصر)',
  'Hay Riad (حي الرياض)',
  'Hay Al Farah (حي الفرح)',
  'Isly / Campus Universitaire (إسلي)',
  'Boulevard Derfoufi (شارع الدرفوفي)',
  'Hay Zaitoun (حي الزيتون)',
  'Boulevard Allal Ben Abdellah',
  'Hay Smara (حي السمارة)',
  'Hay Al Bassatine (حي البساتين)',
  'Zone Industrielle Oujda',
];

// Alias for backward compatibility if imported elsewhere
export const MOROCCAN_CITIES = OUJDA_NEIGHBORHOODS;

export const PARCEL_STATUSES: ParcelStatusInfo[] = [
  {
    key: 'pending',
    label: 'En attente',
    color: Colors.statusPending,
    bgColor: Colors.statusPendingBg,
    icon: '⏳',
  },
  {
    key: 'picked_up',
    label: 'Ramassé',
    color: Colors.statusPickedUp,
    bgColor: Colors.statusPickedUpBg,
    icon: '📦',
  },
  {
    key: 'in_transit',
    label: 'En transit',
    color: Colors.statusInTransit,
    bgColor: Colors.statusInTransitBg,
    icon: '🛵',
  },
  {
    key: 'delivered',
    label: 'Livré',
    color: Colors.statusDelivered,
    bgColor: Colors.statusDeliveredBg,
    icon: '✅',
  },
  {
    key: 'returned',
    label: 'Retourné',
    color: Colors.statusReturned,
    bgColor: Colors.statusReturnedBg,
    icon: '↩️',
  },
];

export const MOCK_PARCELS: Parcel[] = [
  {
    id: '1',
    tracking_number: 'QL-OUJ-00142',
    recipient_name: 'Ahmed Benali',
    recipient_phone: '+212 6 12 34 56 78',
    recipient_address: '45 Boulevard Mohammed V',
    city: 'Oujda — Centre-Ville',
    status: 'delivered',
    cod_amount: 250,
    shipping_cost: 15,
    notes: 'Appeler à l\'arrivée',
    payment_method: 'cash',
    payment_status: 'paid',
    created_at: '2026-08-18T10:30:00Z',
    updated_at: '2026-08-19T14:20:00Z',
    delivered_at: '2026-08-19T14:20:00Z',
    user_id: 'mock-user-1',
  },
  {
    id: '2',
    tracking_number: 'QL-OUJ-00143',
    recipient_name: 'Fatima Zohra El Amrani',
    recipient_phone: '+212 6 98 76 54 32',
    recipient_address: '12 Rue Al Andalous, Hay Al Qods',
    city: 'Oujda — Hay Al Qods',
    status: 'in_transit',
    cod_amount: 380,
    shipping_cost: 15,
    notes: 'Livraison express demandée',
    payment_method: 'card',
    payment_status: 'paid',
    created_at: '2026-08-19T08:15:00Z',
    updated_at: '2026-08-20T09:00:00Z',
    delivered_at: null,
    user_id: 'mock-user-1',
  },
  {
    id: '3',
    tracking_number: 'QL-OUJ-00144',
    recipient_name: 'Youssef Amrani',
    recipient_phone: '+212 6 55 44 33 22',
    recipient_address: '8 Boulevard Derfoufi, Lazaret',
    city: 'Oujda — Lazaret',
    status: 'pending',
    cod_amount: 180,
    shipping_cost: 15,
    notes: 'Colis fragile',
    payment_method: 'cash',
    payment_status: 'pending',
    created_at: '2026-08-20T07:00:00Z',
    updated_at: '2026-08-20T07:00:00Z',
    delivered_at: null,
    user_id: 'mock-user-1',
  },
  {
    id: '4',
    tracking_number: 'QL-OUJ-00145',
    recipient_name: 'Khadija Bouaziz',
    recipient_phone: '+212 6 11 22 33 44',
    recipient_address: '23 Avenue Al Wahda, Hay Salam',
    city: 'Oujda — Hay Salam',
    status: 'picked_up',
    cod_amount: 490,
    shipping_cost: 15,
    notes: '',
    payment_method: 'card',
    payment_status: 'paid',
    created_at: '2026-08-19T16:45:00Z',
    updated_at: '2026-08-20T08:30:00Z',
    delivered_at: null,
    user_id: 'mock-user-1',
  },
  {
    id: '5',
    tracking_number: 'QL-OUJ-00146',
    recipient_name: 'Omar Tazi',
    recipient_phone: '+212 6 77 88 99 00',
    recipient_address: '5 Rue Sidi Yahya',
    city: 'Oujda — Sidi Yahya',
    status: 'returned',
    cod_amount: 150,
    shipping_cost: 15,
    notes: 'Destinataire absent',
    payment_method: 'cash',
    payment_status: 'failed',
    created_at: '2026-08-17T11:00:00Z',
    updated_at: '2026-08-19T16:00:00Z',
    delivered_at: null,
    user_id: 'mock-user-1',
  },
  {
    id: '6',
    tracking_number: 'QL-OUJ-00147',
    recipient_name: 'Sara El Fassi',
    recipient_phone: '+212 6 33 22 11 00',
    recipient_address: '17 Boulevard Allal Ben Abdellah',
    city: 'Oujda — Centre',
    status: 'delivered',
    cod_amount: 320,
    shipping_cost: 15,
    notes: '',
    payment_method: 'card',
    payment_status: 'paid',
    created_at: '2026-08-16T09:00:00Z',
    updated_at: '2026-08-18T11:30:00Z',
    delivered_at: '2026-08-18T11:30:00Z',
    user_id: 'mock-user-1',
  },
  {
    id: '7',
    tracking_number: 'QL-OUJ-00148',
    recipient_name: 'Mohammed Alaoui',
    recipient_phone: '+212 6 44 55 66 77',
    recipient_address: '30 Campus Universitaire Isly',
    city: 'Oujda — Isly',
    status: 'in_transit',
    cod_amount: 275,
    shipping_cost: 15,
    notes: 'Livrer à la faculté des sciences',
    payment_method: 'cash',
    payment_status: 'pending',
    created_at: '2026-08-19T14:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    delivered_at: null,
    user_id: 'mock-user-1',
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalParcels: 7,
  pendingParcels: 1,
  inTransitParcels: 2,
  deliveredParcels: 2,
  returnedParcels: 1,
  totalCodAmount: 2045,
  deliveredCodAmount: 570,
};
