export const colors = {
  primary: "#5C5BDB",
  primaryLight: "#EBEBFC",
  primaryDark: "#3C3489",
  secondary: "#FF4D6D",
  secondaryLight: "#FFEBF0",
  background: "#F7F7FF",
  surface: "#FFFFFF",
  surfaceVariant: "#F0F0FC",
  text: "#3C3489",
  textSecondary: "#7F77DD",
  textMuted: "#7F77DD",
  textInverse: "#FFFFFF",
  border: "#CECBF6",
  borderFocus: "#5C5BDB",
  cta: "#FF4D6D",
  badge: "#FFD166",
  highlight: "#FFD166",
  success: "#10B981",
  successLight: "#D1FAE5",
  error: "#EF4444",
  errorLight: "#FEE2E2",
  warning: "#FFD166",
  warningLight: "#FFF8E7",
  transparent: "transparent",
  overlay: "rgba(60, 52, 137, 0.4)",
} as const;

export type ColorToken = keyof typeof colors;
