export const colors = {
  primary: "#0066FF",
  primaryLight: "#E0F2FE",
  primaryDark: "#0047AB",
  secondary: "#FF5A35",
  secondaryLight: "#FFE8DF",
  background: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceVariant: "#F7FAFC",
  text: "#1A202C",
  textSecondary: "#718096",
  textMuted: "#A0AEC0",
  textInverse: "#FFFFFF",
  border: "#E2E8F0",
  borderFocus: "#0066FF",
  success: "#10B981",
  successLight: "#D1FAE5",
  error: "#EF4444",
  errorLight: "#FEE2E2",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  transparent: "transparent",
  overlay: "rgba(15, 23, 42, 0.4)",
} as const;

export type ColorToken = keyof typeof colors;
